// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NWZWalks.Api.Data;

#nullable disable

namespace NWZWalks.Api.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20240528231510_fakedata")]
    partial class fakedata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NWZWalks.Api.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("NWZWalks.Api.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WalkDifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("WalkDifficultyId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NWZWalks.Api.Models.Domain.WalkDifficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WalkDifficulty");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2df9e37b-ad60-4b9e-a8a3-d943c8ddf57d"),
                            Code = "codeName0"
                        },
                        new
                        {
                            Id = new Guid("dae1250a-d1f4-49f7-ad12-fea7482b319b"),
                            Code = "codeName1"
                        },
                        new
                        {
                            Id = new Guid("c82f864d-37e6-46e5-8d69-309b52469032"),
                            Code = "codeName2"
                        },
                        new
                        {
                            Id = new Guid("7895c14c-09b5-4e75-af89-7acc301e0e2a"),
                            Code = "codeName3"
                        },
                        new
                        {
                            Id = new Guid("3df23f0c-e38f-4fe3-9d50-0b8483b1f5af"),
                            Code = "codeName4"
                        },
                        new
                        {
                            Id = new Guid("c959409e-c464-44ae-8544-bf4f37d98ef9"),
                            Code = "codeName5"
                        },
                        new
                        {
                            Id = new Guid("8fd89747-c83c-4fe7-a87e-f8ec660dc0d2"),
                            Code = "codeName6"
                        },
                        new
                        {
                            Id = new Guid("9b535872-d82f-47b3-aeea-d9e9068e12c0"),
                            Code = "codeName7"
                        },
                        new
                        {
                            Id = new Guid("6db2a021-2853-48cc-a651-7315f9e1f31d"),
                            Code = "codeName8"
                        },
                        new
                        {
                            Id = new Guid("32a7d96d-7fd3-477a-ac0c-3dc5d6618cd9"),
                            Code = "codeName9"
                        },
                        new
                        {
                            Id = new Guid("64e67170-33c5-41f2-b811-0e692d657dd0"),
                            Code = "codeName10"
                        },
                        new
                        {
                            Id = new Guid("7553afa9-e8e7-4b4a-ab5e-87317ad653cd"),
                            Code = "codeName11"
                        },
                        new
                        {
                            Id = new Guid("7bafb2e3-c630-49e5-b3c1-307a051205b3"),
                            Code = "codeName12"
                        },
                        new
                        {
                            Id = new Guid("18bfdc1a-3750-45f3-a9ee-8da0f86034de"),
                            Code = "codeName13"
                        },
                        new
                        {
                            Id = new Guid("0b419edc-84c2-456a-8c22-448e0f9d370a"),
                            Code = "codeName14"
                        },
                        new
                        {
                            Id = new Guid("51dc0719-90d6-4447-990d-fa615deb6b76"),
                            Code = "codeName15"
                        },
                        new
                        {
                            Id = new Guid("ea92758c-3952-4e92-9018-4e79640e6678"),
                            Code = "codeName16"
                        },
                        new
                        {
                            Id = new Guid("1992df25-fe79-4a31-93c0-bbe41c352727"),
                            Code = "codeName17"
                        },
                        new
                        {
                            Id = new Guid("089df368-06cc-4932-a3bc-dda27d8726fc"),
                            Code = "codeName18"
                        },
                        new
                        {
                            Id = new Guid("20a5925f-5a51-4136-8bc4-6b031449bec1"),
                            Code = "codeName19"
                        },
                        new
                        {
                            Id = new Guid("a0f6b199-d118-484b-9ef0-906eef59401f"),
                            Code = "codeName20"
                        },
                        new
                        {
                            Id = new Guid("7497dc4d-cc5d-4cb3-a5ea-86bb7af85a2c"),
                            Code = "codeName21"
                        },
                        new
                        {
                            Id = new Guid("51b2aaf8-16be-433c-a42e-456de4a34d94"),
                            Code = "codeName22"
                        },
                        new
                        {
                            Id = new Guid("8b99248a-59c5-4c8b-8ae8-de73a8dd0d45"),
                            Code = "codeName23"
                        },
                        new
                        {
                            Id = new Guid("531520ce-e3b6-444e-a840-6f6b89fee954"),
                            Code = "codeName24"
                        },
                        new
                        {
                            Id = new Guid("5186aa69-5eaa-4120-9c0a-a0dbe4deb81a"),
                            Code = "codeName25"
                        },
                        new
                        {
                            Id = new Guid("a0320d6f-9443-4888-9c21-01d751f45f15"),
                            Code = "codeName26"
                        },
                        new
                        {
                            Id = new Guid("7fb26f08-3520-4d4c-a79c-5d78c74c5035"),
                            Code = "codeName27"
                        },
                        new
                        {
                            Id = new Guid("709bcb67-0cce-41ef-9342-56f6b2aed31b"),
                            Code = "codeName28"
                        },
                        new
                        {
                            Id = new Guid("9de22ec9-c394-4b32-b003-b68c3bbbd8ef"),
                            Code = "codeName29"
                        },
                        new
                        {
                            Id = new Guid("ca1e234f-b590-48c9-9a7b-a661a73656d2"),
                            Code = "codeName30"
                        },
                        new
                        {
                            Id = new Guid("d1d19441-ae16-4e9a-b4bc-533e1d1dbf80"),
                            Code = "codeName31"
                        },
                        new
                        {
                            Id = new Guid("03993c45-019c-438b-be07-e015e8813677"),
                            Code = "codeName32"
                        },
                        new
                        {
                            Id = new Guid("b365508b-8123-4194-9d08-daa94bcd15ee"),
                            Code = "codeName33"
                        },
                        new
                        {
                            Id = new Guid("dce52e9a-97d5-41ba-ae7f-29306172f101"),
                            Code = "codeName34"
                        },
                        new
                        {
                            Id = new Guid("0342d4a6-c73f-416e-a05d-b05faa63d87b"),
                            Code = "codeName35"
                        },
                        new
                        {
                            Id = new Guid("7bec5fcb-4a27-4a34-8372-7b5f6e7a0488"),
                            Code = "codeName36"
                        },
                        new
                        {
                            Id = new Guid("0354c9f7-f9df-47da-adc8-25bff8d7923f"),
                            Code = "codeName37"
                        },
                        new
                        {
                            Id = new Guid("6a57b417-01e7-4dc2-8bce-4250903120df"),
                            Code = "codeName38"
                        },
                        new
                        {
                            Id = new Guid("f23772a1-2343-48fe-886c-ecb83af74af7"),
                            Code = "codeName39"
                        },
                        new
                        {
                            Id = new Guid("9bb7b4f1-9b05-4205-8cac-52d5a5388c57"),
                            Code = "codeName40"
                        },
                        new
                        {
                            Id = new Guid("2ad6c10d-177f-4a63-a196-e0097e71d31d"),
                            Code = "codeName41"
                        },
                        new
                        {
                            Id = new Guid("a8ccc4a4-c20b-4f56-b357-af566312152d"),
                            Code = "codeName42"
                        },
                        new
                        {
                            Id = new Guid("cd73c1be-b65e-448c-9984-55c427685f63"),
                            Code = "codeName43"
                        },
                        new
                        {
                            Id = new Guid("7b156e16-a564-47e4-b8b4-3fb1cd0d928b"),
                            Code = "codeName44"
                        },
                        new
                        {
                            Id = new Guid("fb970037-1b30-4e58-99ee-20c1a4fe725d"),
                            Code = "codeName45"
                        },
                        new
                        {
                            Id = new Guid("28cec6b0-e51c-4b6d-a1d9-7f99bed4d106"),
                            Code = "codeName46"
                        },
                        new
                        {
                            Id = new Guid("d79664ce-1617-4f47-a554-79e667fc4c97"),
                            Code = "codeName47"
                        },
                        new
                        {
                            Id = new Guid("64c944ef-2f45-4604-b05d-714527cbf794"),
                            Code = "codeName48"
                        },
                        new
                        {
                            Id = new Guid("6a25231c-4465-4b58-a4f3-7891ab24959a"),
                            Code = "codeName49"
                        });
                });

            modelBuilder.Entity("NWZWalks.Api.Models.Domain.Walk", b =>
                {
                    b.HasOne("NWZWalks.Api.Models.Domain.Region", "Region")
                        .WithMany("Walks")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NWZWalks.Api.Models.Domain.WalkDifficulty", "WalkDifficulty")
                        .WithMany()
                        .HasForeignKey("WalkDifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("WalkDifficulty");
                });

            modelBuilder.Entity("NWZWalks.Api.Models.Domain.Region", b =>
                {
                    b.Navigation("Walks");
                });
#pragma warning restore 612, 618
        }
    }
}
