// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NWZWalks.Api.Data;

#nullable disable

namespace NWZWalks.Api.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20240529011627_fakedata1")]
    partial class fakedata1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NWZWalks.Api.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("NWZWalks.Api.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WalkDifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("WalkDifficultyId");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b5b6f14-8672-4604-a699-ce219c93f105"),
                            Length = 0.0,
                            Name = "9pchB",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("63e51d8e-fd1d-4e91-8cdc-56cec4f40766"),
                            Length = 1.0,
                            Name = "z2Jva",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("e22debf2-8596-4fdc-85e8-4ca67293dd14"),
                            Length = 2.0,
                            Name = "JVcbA",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("82f5df5a-398f-49cb-9fee-297546f3df6b"),
                            Length = 3.0,
                            Name = "FxFAe",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("bed3e9d7-d2be-4ade-abad-c924f3547c4c"),
                            Length = 4.0,
                            Name = "kibuL",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("2dab0e88-a7d7-42a3-bfe9-60142da743d2"),
                            Length = 5.0,
                            Name = "vCkpx",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("352840a6-721a-42de-b3b6-847234f3378e"),
                            Length = 6.0,
                            Name = "2oame",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("27eb975d-e724-40d8-95e8-5c859b0ba1e6"),
                            Length = 7.0,
                            Name = "P9YpD",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("83b6ce00-4108-4375-a105-2043a36a44e9"),
                            Length = 8.0,
                            Name = "RZPcG",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("f99d382a-bf9f-4556-9f65-9e085340b933"),
                            Length = 9.0,
                            Name = "n5CWB",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("c4e9b809-da5f-4b7a-9b94-6bce210e560e"),
                            Length = 10.0,
                            Name = "trBIp",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("3d0e1afc-bcb1-4c0e-ade8-558cf7286b24"),
                            Length = 11.0,
                            Name = "NrS3a",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("f5070608-8b15-4904-aee7-876c0a0b8fb0"),
                            Length = 12.0,
                            Name = "OyAls",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("229df89d-8678-490b-bf4c-fbdc60cdc487"),
                            Length = 13.0,
                            Name = "7ctKo",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("091a5b5d-d927-426a-bb86-42c75b20da8b"),
                            Length = 14.0,
                            Name = "nJBuC",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("626016b4-5bcd-47dc-afb5-84aecda614a3"),
                            Length = 15.0,
                            Name = "0AwPV",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("eac65142-e370-4936-82f9-e4c49a8ef34e"),
                            Length = 16.0,
                            Name = "6IPQN",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("99cb1e0a-ab9b-4f49-b0a8-4a5acde275b3"),
                            Length = 17.0,
                            Name = "XZz7Z",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("77e320d0-3e1c-4fb9-a365-92d388dedef6"),
                            Length = 18.0,
                            Name = "5VKYJ",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("e7fa6fee-374b-4e28-a628-0cb6d69806df"),
                            Length = 19.0,
                            Name = "LIcU7",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("c10b1cdb-b7a2-4f34-9ce0-d389d7f1c5c6"),
                            Length = 20.0,
                            Name = "fJ0oE",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("ef7af70f-654f-4d9e-bd63-689912078d0a"),
                            Length = 21.0,
                            Name = "8Rviv",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("d5d87ce8-31e5-4bf5-842d-9ae662a2f1c2"),
                            Length = 22.0,
                            Name = "OqASo",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("d76ce6dd-9e28-4393-b1f5-21f895933b7f"),
                            Length = 23.0,
                            Name = "X22DI",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("238ff8b2-a543-42c4-beb3-5cfdb0ad4066"),
                            Length = 24.0,
                            Name = "ICkPQ",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("03d047f6-2f1a-4a1a-b4bf-c7e050a1f2e9"),
                            Length = 25.0,
                            Name = "coYQ9",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("4bde1b3d-c1d2-46b1-a103-69013ad378eb"),
                            Length = 26.0,
                            Name = "Rw6Nx",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("40159717-ddcf-4ca2-8f96-cf28dda0db73"),
                            Length = 27.0,
                            Name = "BjVxH",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("9a515493-72eb-4dfa-8f8f-bc80a758f07f"),
                            Length = 28.0,
                            Name = "rSOIw",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("946daa12-2f69-4a50-848e-1bc35c681740"),
                            Length = 29.0,
                            Name = "gHZ2D",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("5edb7a4e-6f3d-45e3-b004-89fee7c39577"),
                            Length = 30.0,
                            Name = "K2rAP",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("36ec2533-2980-4a49-9884-d33ec674f27e"),
                            Length = 31.0,
                            Name = "syNCO",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("2ab15d32-8c9d-42f5-94c3-e14000453d7d"),
                            Length = 32.0,
                            Name = "dUH65",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("26c17b07-0062-454a-952b-a1bfcbf51a79"),
                            Length = 33.0,
                            Name = "8hCEd",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("5b07429f-3ee7-4664-ad16-09a00a3ed4ca"),
                            Length = 34.0,
                            Name = "KzNgp",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("07980262-edc7-4728-b185-c929a255c686"),
                            Length = 35.0,
                            Name = "8XQ1u",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("0a82981b-df6a-4224-a681-19943f74f768"),
                            Length = 36.0,
                            Name = "1OMVp",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("64c7ac43-c587-4bb2-b3ee-7bf4adc90558"),
                            Length = 37.0,
                            Name = "mv0eX",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("a446acec-71fc-4146-951f-e5875c889a36"),
                            Length = 38.0,
                            Name = "RK29s",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("b6974bb6-ed49-40a7-9434-b0f99da636ac"),
                            Length = 39.0,
                            Name = "T9f72",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("693e1eba-e675-4256-8c72-d5b951b4740f"),
                            Length = 40.0,
                            Name = "VAVDJ",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("daca740b-8396-43a7-9964-94ace3b6e059"),
                            Length = 41.0,
                            Name = "gA5Pz",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("3f857178-0fc6-4e6d-a7a4-5e1c564ce2c7"),
                            Length = 42.0,
                            Name = "qcwV7",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("9a02bd63-b4db-410b-b866-62faceb6d809"),
                            Length = 43.0,
                            Name = "rUixe",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("ff4e0d01-c2ab-403d-9c37-e5396d579cc3"),
                            Length = 44.0,
                            Name = "ereer",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("38fdb9b7-8def-466a-8c91-caa2b1498696"),
                            Length = 45.0,
                            Name = "cvdhK",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("d212ce48-4bde-4d88-819d-0905e83aa87c"),
                            Length = 46.0,
                            Name = "J2ld7",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("6680d746-e52e-43bd-9093-20da42699a53"),
                            Length = 47.0,
                            Name = "v9jDu",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("10d9feb1-4514-4615-89dd-e6ab97048a82"),
                            Length = 48.0,
                            Name = "R3mNn",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        },
                        new
                        {
                            Id = new Guid("44357487-344a-4c96-a69b-226bbe7902ac"),
                            Length = 49.0,
                            Name = "0NJ4x",
                            RegionId = new Guid("ed52fca0-6d0d-421e-046c-08dc73e2ee27"),
                            WalkDifficultyId = new Guid("9d258237-f3dc-49dc-93e9-03e124c8a90c")
                        });
                });

            modelBuilder.Entity("NWZWalks.Api.Models.Domain.WalkDifficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WalkDifficulty");
                });

            modelBuilder.Entity("NWZWalks.Api.Models.Domain.Walk", b =>
                {
                    b.HasOne("NWZWalks.Api.Models.Domain.Region", "Region")
                        .WithMany("Walks")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NWZWalks.Api.Models.Domain.WalkDifficulty", "WalkDifficulty")
                        .WithMany()
                        .HasForeignKey("WalkDifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("WalkDifficulty");
                });

            modelBuilder.Entity("NWZWalks.Api.Models.Domain.Region", b =>
                {
                    b.Navigation("Walks");
                });
#pragma warning restore 612, 618
        }
    }
}
